# Generated by Django 5.0.7 on 2024-07-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.TextField(default='English'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default='Your name'),
        ),
    ]
