# Generated by Django 5.0.7 on 2024-07-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_languages_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
